import { useEffect, useRef } from 'react';
import Lottie, { AnimationItem } from 'lottie-web';
import { Wrapper } from './Animation.styles';

/**
 * **src**: Should be an imported json file generated by bodymovin
 */
type AnimationProps = {
  src: unknown;
  className?: string;
};

const Animation = ({ src, className }: AnimationProps) => {
  const { current: animationId } = useRef('asdasdasdasd');
  const loadingAnimationItem = useRef<AnimationItem | null>(null);

  useEffect(() => {
    // To prevent animation from rendering more times during development
    // this only happens if the animation was not set

    if (loadingAnimationItem.current === null) {
      loadingAnimationItem.current = Lottie.loadAnimation({
        container: document.querySelector(`#${animationId}`) as HTMLDivElement,
        animationData: src,
        renderer: 'svg'
      });
    }
  }, [animationId, src]);

  return <Wrapper id={animationId} className={className} />;
};

export default Animation;
