# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build / Release Mac

env: 
  GITHUB_TOKEN: "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"
  REACT_APP_VERSION: $npm_package_version
  REACT_APP_NAME: $npm_package_name

on:
  push:
    # https://stackoverflow.com/questions/61891328/trigger-github-action-only-on-new-tags
    tags: 
      - "*"
    branches: [ main ]
    
jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm run release:mac --if-present
  
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm run release:windows --if-present
