name: Build / Release Mac

env: 
  GITHUB_TOKEN: "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"

on:
  workflow_dispatch:
    

  # push:
    # branches: 
      # - main
    # tags
      # - v*
    
jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Get package info
      id: package
      uses: codex-team/action-nodejs-package-info@v1

    - name: create env file
      run: |
        touch .env
        echo "REACT_APP_VERSION=${{ steps.package.outputs.version }}" >> .env
        cat .env

    - name: "Install dependencies"
      run: npm ci
    - name: "Run build and release"
      run: npm run release:mac --if-present
  