import { useEffect, useRef } from 'react';
import Lottie, { AnimationItem } from 'lottie-web';
import { Wrapper } from './Animation.styles';

/**
 * **src**: Should be an imported json file generated by bodymovin
 */
type AnimationProps = {
  src: unknown;
  className?: string;
};

const Animation = ({ src, className }: AnimationProps) => {
  const container = useRef<HTMLDivElement>(null);
  const loadingAnimationItem = useRef<AnimationItem>();

  useEffect(() => {
    loadingAnimationItem.current = Lottie.loadAnimation({
      container: container.current as HTMLDivElement,
      animationData: src,
      renderer: 'svg'
    });

    return () => {
      (loadingAnimationItem.current as AnimationItem).destroy();
    };
  }, [src]);

  return <Wrapper ref={container} className={className} />;
};

export default Animation;
