import { MutableRefObject, useEffect, useRef } from 'react';
// Using lottie light, as full lottie uses eval() to work, and eval() is blocked by the Content Security Policy
import Lottie, { AnimationItem } from 'lottie-web/build/player/lottie_light';
import { Wrapper } from './Animation.styles';

/**
 * **src**: Should be an imported json file generated by bodymovin
 */
type AnimationProps = {
  src: unknown;
  className?: string;
};

const Animation = ({ src, className }: AnimationProps) => {
  const container = useRef<HTMLDivElement>(null);
  const loadingAnimationItem = useRef() as MutableRefObject<AnimationItem>;

  useEffect(() => {
    loadingAnimationItem.current = Lottie.loadAnimation({
      container: container.current as HTMLDivElement,
      animationData: src,
      renderer: 'svg'
    });

    return () => {
      loadingAnimationItem.current.destroy();
    };
  }, [src]);

  return <Wrapper ref={container} className={className} />;
};

export default Animation;
